- name: Setup Production and Staging Environments
  hosts: all
  become: yes
  vars:
    k3s_version: "v1.31.3-rc1+k3s1"
    docker_compose_version: "1.29.2"
    node_exporter_version: "1.5.0"
    ubuntu_release: "focal"

  tasks:
    # Common setup: Update and install prerequisites
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present

    # Install Docker (required for both environments)
    # Step 1: Create directory for APT keyrings
    - name: Create directory for apt keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    # Step 2: Download and dearmor the Docker GPG key
    - name: Download and dearmor Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    # Step 3: Set permissions on Docker GPG key
    - name: Set permissions on Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    # Step 4: Add the Docker repository
    - name: Add Docker repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_release }} stable
        mode: '0644'

    # Step 5: Update APT package index
    - name: Update APT package index
      apt:
        update_cache: yes
        force_apt_get: yes

    # Step 6: Install Docker packages
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose
          - docker-compose-plugin
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    # Install Node Exporter
    - name: Create a directory for Node Exporter
      file:
        path: /opt/node_exporter
        state: directory
        mode: '0755'

    - name: Download Node Exporter binary
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter binary
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt/node_exporter
        remote_src: yes

    - name: Move Node Exporter binary to /usr/local/bin
      copy:
        remote_src: yes
        src: /opt/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0755'

    - name: Create a systemd service file for Node Exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started
    # Environment-specific setup: k3s for production
    - name: Download and install k3s (production environment)
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Start k3s server (production environment)
      systemd:
        name: k3s
        enabled: yes
        state: started

    - name: Download Kompose binary (production environment)
      get_url:
        url: "https://github.com/kubernetes/kompose/releases/download/v1.26.1/kompose-linux-amd64"
        dest: "/usr/local/bin/kompose"
        mode: '0755'

    - name: Verify Kompose installation (production environment)
      command: kompose version
      register: kompose_version_output
      failed_when: kompose_version_output.rc != 0

    - name: Display Kompose version (production environment)
      debug:
        var: kompose_version_output.stdout
